{{- if .Values.provider.standalone }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.envoy-labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway-api-inference-extension.envoy-selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.provider.standalone.envoy.servicePort | default 8081 }}
      protocol: TCP
      targetPort: {{ .Values.provider.standalone.envoy.servicePort | default 8081 }}
  type: ClusterIP
{{- end }}
