{{- range .Values.inferenceObjectives }}
---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceObjective
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" $ | nindent 4 }}
spec:
  priority: {{ .priority }}
  poolRef:
    group: {{ .Values.inferenceExtension.apiVersion }}
    name: {{ $.Release.Name }}
{{- end }}
